const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
const PORT = process.env.PORT || 5000;
app.use(cors());
app.use(express.json());
app.use('/api', require('./routes'));
app.get('/', (req, res) => res.json({ message: 'Sunny BK CRM API running', version: '1.0.0' }));
app.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT} | Email: ${process.env.GMAIL_USER || 'not configured'}`));
